apiVersion: v1
kind: Secret
metadata:
  name: jenkins-master-secret
  namespace: NAMESPACE
type: Opaque
data:
  admin-pass: NmhGNVd1ZnJlZmVyZmU=    # 6hF5Wufreferfe
  admin-user: MzEyLWFkbWlu            # 312-admin
  github-branches: ZmVhdHVyZS1kZXZlbG9wLXlhaG9yLio= #feature-develop-yahor.*
  github-org: Y2ktY2QtcGlwZQ==                # ci-cd-pipe
  github-pass: Z2hwX3dEalp2dmFGZ3JiNFBiTTBxRElSYk9pZWRyTVZnNDM2Q3FVeA==
  github-repo: Y2ljZC1kZW1vLTIyYw==
  github-user: V2FyZmlyZTE=
